### ISSUE TITLE
degree definition seems wrong

### ISSUE THREAD

**Issue by bimmlerd** [g-trees/g_trees#6]
The definition of degree seems wrong:

https://github.com/g-trees/g_trees/blob/333dfe14fee7a69337f038173b3f225fd2d31519/src/main.tsx#L435

According to wikipedia, the degree of a node is the number of children, whereas the degree of a tree is the maximal degree of any of its nodes.

**Comment by AljoschaMeyer** [comment]
The definition in that paragraph is definitely off — `d` isn't even quantified. Must have been some editing mishap.

In principle, the definitions are *consistent*; we use "arity" for the conventional max-degree-of-any-vertex definition, and "degree" for only a single vertex. A tree *is* a vertex, after all. But I can see that this can be confusing. Since we only use "degree" once anyways, I'll simply remove the definition and inline it at its one usage.

Thank you for catching this!
